"""fifth migration

Revision ID: fce740a23fd9
Revises: 2bbd9a81d3cc
Create Date: 2023-03-28 00:30:59.435692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fce740a23fd9'
down_revision = '2bbd9a81d3cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_measure', sa.Integer(), nullable=True))
        batch_op.drop_column('stock')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('stock_measure')

    # ### end Alembic commands ###
